### ISSUE TITLE
S2 - 14 - Membuat Halaman Input Donasi Buku

### ISSUE THREAD

**Issue by tasymae** [SI-RPL-2022/SI4301_EasyLibrary#14]
Sebagai petugas perpustakaan, saya ingin memasukkan buku yang user donasikan
![Input Donasi](https://user-images.githubusercontent.com/84862602/164452362-ba2aadf8-20fa-4ee3-8097-29608a18b6ca.png)

**Comment by tienfkusumasari** [comment]
done utk crete dan updaqte serta delete tp detail belum ada (SP3)
