### ISSUE TITLE
S3 - 18 - Membuat halaman detail data peminjaman, dan data pengembalian

### ISSUE THREAD

**Issue by tasymae** [SI-RPL-2022/SI4301_EasyLibrary#18]
Sebagai admin, saya ingin melihat detail dari data peminjaman, dan data pengembalian
![Detail Peminjaman Buku (1)](https://user-images.githubusercontent.com/84862602/173856234-0803308e-11b1-4b8c-ad60-122faf11b434.png)
![Pengembalian Buku](https://user-images.githubusercontent.com/67242667/172797500-521a332b-99c6-4d0a-97e1-08e34db0b3a7.png)

**Comment by tienfkusumasari** [comment]
done (SP3)
