### ISSUE TITLE
S3 - 19 - Membuat halaman update Detail Data Peminjaman

### ISSUE THREAD

**Issue by tasymae** [SI-RPL-2022/SI4301_EasyLibrary#19]
Sebagai admin, saya ingin melakukan pembaruan terkait detail dari data peminjaman
![Update Peminjaman Buku](https://user-images.githubusercontent.com/84862602/173856278-868b240c-24b7-42ca-bac6-061f4962da24.png)

**Comment by tienfkusumasari** [comment]
close (SP3)
