### ISSUE TITLE
S3 - 20 - Melihat halaman tampilan Data User

### ISSUE THREAD

**Issue by tasymae** [SI-RPL-2022/SI4301_EasyLibrary#20]
Sebagai admin, saya ingin melihat list dari tampilan data user yang menggunakan EasyLibrary 
![DATA USER](https://user-images.githubusercontent.com/84862602/173845069-4832bd87-1189-434b-9d26-7a3be4537e2c.png)

**Comment by tienfkusumasari** [comment]
done (SP3) mockup belum di update
