### ISSUE TITLE
S3 - 23 - Membuat halaman report

### ISSUE THREAD

**Issue by tasymae** [SI-RPL-2022/SI4301_EasyLibrary#23]
Sebagai admin, dan  petugas perpustakaan ingin bisa melihat statistik dari website perpustakaa
![Report](https://user-images.githubusercontent.com/92176782/175959021-ff8645ef-4acc-4a1d-9698-03002ffa770a.png)
n

**Comment by tienfkusumasari** [comment]
issue harus diperbaiki

**Comment by tienfkusumasari** [comment]
belum dibuat baru tampilan saja (SP3)

**Comment by tienfkusumasari** [comment]
close (SP3)
